version: '3.5'

services:
  convid-accounts-frontend:
    image: convid/convid-accounts-frontend
    build: .
      # context: .
      # args: 
      #   - NODE_ENV=production
      #   - REACT_APP_BACKEND_API_URL=BUILD_BACKEND_API_URL